'use client'

import { useMemo, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, BarChart3, Check, CircleGauge, FileText, Gauge, LockKeyhole, Save, Ship, SlidersHorizontal, Target, Waves, Zap } from 'lucide-react'

const routeContent = {
  '/voyage-planner': { eyebrow: 'FIXTURE WORKBENCH', title: 'Voyage Planner', description: 'Build an optimal charter plan from cargo, route and contract requirements.', heading: 'Voyage input', action: 'Generate optimal charter plan' },
  '/freight-forecast': { eyebrow: 'PREDICTIVE MARKET INTELLIGENCE', title: 'Freight Forecast', description: 'Project the freight curve before you commit capital.', heading: 'Rate curve & confidence band', action: 'Refresh forecast' },
  '/vessel-optimizer': { eyebrow: 'FLEET MATCHING ENGINE', title: 'Vessel Optimizer', description: 'Compare vessel classes against fit, cost and operational constraints.', heading: 'AI vessel comparison', action: 'Inspect selected vessel' },
  '/port-compatibility': { eyebrow: 'PORT ENGINEERING', title: 'Port Compatibility', description: 'Validate berth, draft and operational compatibility before fixture execution.', heading: 'Port assessment', action: 'Run compatibility check' },
  '/risk-intelligence': { eyebrow: 'EXPOSURE MONITORING', title: 'Risk Intelligence', description: 'Surface market, operational and geopolitical exposure across the voyage.', heading: 'Risk decomposition', action: 'Review risk factors' },
  '/cost-optimization': { eyebrow: 'VOYAGE ECONOMICS', title: 'Cost Optimization', description: 'Model voyage economics and identify the best risk-adjusted savings.', heading: 'Cost stack', action: 'Compare strategies' },
  '/charter-strategy': { eyebrow: 'DECISION ENGINE', title: 'Charter Strategy', description: 'Translate market intelligence into an executable chartering strategy.', heading: 'Strategy recommendation', action: 'Lock partial position' },
  '/what-if-simulator': { eyebrow: 'SCENARIO LAB', title: 'What-If Simulator', description: 'Stress-test timing, freight and bunker assumptions before you commit.', heading: 'Scenario controls', action: 'Run scenario' },
  '/reports': { eyebrow: 'EXECUTIVE OUTPUTS', title: 'Reports', description: 'Export a decision-ready recap for commercial and operations stakeholders.', heading: 'Decision recap', action: 'Export report' },
} as const

type Route = keyof typeof routeContent

const vesselScores = [['Handysize', 62], ['Supramax', 78], ['Panamax', 94], ['Capesize', 71]]

export default function VoyageIQModulePage({ route }: { route: Route }) {
  const content = routeContent[route]
  const [cargo, setCargo] = useState(80000)
  const [congestion, setCongestion] = useState('Low')
  const [selectedVessel, setSelectedVessel] = useState('Panamax')
  const [notice, setNotice] = useState('')
  const [range, setRange] = useState('30D')
  const forecast = Math.max(16.8, 19.8 + (cargo - 80000) / 100000 - (congestion === 'High' ? -1.2 : congestion === 'Medium' ? -0.5 : 0))
  const risk = Math.min(92, Math.round(32 + (cargo - 80000) / 5000 + (congestion === 'High' ? 19 : congestion === 'Medium' ? 8 : 0) + (selectedVessel === 'Capesize' ? 7 : 0)))
  const totalCost = Math.round(cargo * forecast + 410000 + risk * 850)
  const strategy = forecast < 20.2 && risk < 48 ? 'PARTIAL LOCK' : forecast < 20.2 ? 'WAIT' : 'BUY NOW'
  const chartPoints = useMemo(() => range === '7D' ? [21.4, 21.1, 20.9, 20.8] : range === '15D' ? [21.4, 21.1, 20.8, 20.4, 20.1] : [21.8, 21.4, 21.2, 20.9, 20.6, 20.1, forecast], [forecast, range])
  const run = () => { setNotice(`${content.title} analysis generated successfully`); window.setTimeout(() => setNotice(''), 2600) }

  return <div className="space-y-5">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 text-[11px] font-semibold uppercase tracking-[.16em] text-[#087cb8]">{content.eyebrow}</div><h1 className="text-[30px] font-bold tracking-[-.03em] text-[#0b1f3a]">{content.title}</h1><p className="mt-1 text-sm text-[#6d7c8f]">{content.description}</p></div><button onClick={run} className="flex items-center gap-2 self-start rounded-md bg-[#0b1f3a] px-4 py-2.5 text-xs font-semibold text-white md:self-auto"><Zap className="size-4 text-[#58c7b3]" /> {content.action}</button></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Forecast freight" value={`$${forecast.toFixed(2)} / MT`} detail="AI projection" icon={BarChart3} /><Kpi label="Risk score" value={`${risk} / 100`} detail={risk < 40 ? 'Low-moderate' : 'Elevated'} icon={CircleGauge} /><Kpi label="Estimated cost" value={`$${(totalCost / 1000000).toFixed(2)}M`} detail={`$${Math.round(totalCost / cargo)} / MT`} icon={Gauge} /><Kpi label="Recommended action" value={strategy} detail="Engine output" icon={Target} /></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_330px]">
      <section className="rounded-md border border-[#d8dee8] bg-white p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-sm font-bold uppercase tracking-[.1em] text-[#0b1f3a]">{content.heading}</h2><p className="mt-1 text-xs text-[#7b8999]">Muara Berau → Paradip · Thermal Coal · 12–15 Oct 2026</p></div><span className="rounded-full bg-[#e7f8f2] px-2.5 py-1 text-[10px] font-semibold text-[#087d69]">LIVE MODEL</span></div>
        {route === '/voyage-planner' && <div className="grid gap-4 sm:grid-cols-2"><Field label="Origin port" value="Muara Berau / Indonesia" /><Field label="Destination" value="Paradip Port / India" /><Field label="Commodity" value="Thermal Coal" /><label className="flex flex-col gap-2"><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#7b8999]">Cargo quantity · {cargo.toLocaleString()} MT</span><input type="range" min="40000" max="120000" step="5000" value={cargo} onChange={(e) => setCargo(Number(e.target.value))} className="accent-[#087cb8]" /></label><Field label="Contract duration" value="Short-Term / 30 Days" /><Field label="Vessel preference" value={selectedVessel} /></div>}
        {route === '/freight-forecast' && <><div className="mb-4 flex gap-1 rounded-md border border-[#d8dee8] p-1 w-fit">{['7D', '15D', '30D'].map((item) => <button key={item} onClick={() => setRange(item)} className={`rounded px-3 py-1.5 text-[10px] font-semibold ${range === item ? 'bg-[#0b1f3a] text-white' : 'text-[#708096]'}`}>{item}</button>)}</div><div className="rounded-md bg-[#f7fafc] p-4"><div className="flex h-56 items-end gap-2">{chartPoints.map((point, index) => <div key={`${point}-${index}`} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t bg-[#0c9b86]" style={{ height: `${Math.max(24, (point - 18) * 28)}px`, opacity: index < chartPoints.length - 1 ? .35 : 1 }} /><span className="font-mono text-[10px] text-[#8290a1]">{point.toFixed(1)}</span></div>)}</div></div></>}
        {route === '/vessel-optimizer' && <div className="grid gap-3 sm:grid-cols-2">{vesselScores.map(([name, score]) => <button key={name} onClick={() => setSelectedVessel(name)} className={`rounded-md border p-4 text-left ${selectedVessel === name ? 'border-[#087cb8] bg-[#f1f8fc]' : 'border-[#e1e7ee]'}`}><div className="flex items-center justify-between"><span className="font-semibold text-[#0b1f3a]">{name}</span><span className="font-mono text-xl font-semibold text-[#087cb8]">{score}</span></div><div className="mt-3 h-1.5 rounded-full bg-[#e7edf3]"><div className="h-full rounded-full bg-[#0c9b86]" style={{ width: `${score}%` }} /></div><div className="mt-3 grid grid-cols-3 text-[10px] text-[#718095]"><span>Cargo fit<br /><b className="text-[#0b1f3a]">{score - 3}%</b></span><span>Port fit<br /><b className="text-[#0b1f3a]">{score + 2}%</b></span><span>Availability<br /><b className="text-[#0b1f3a]">18 ships</b></span></div></button>)}</div>}
        {(route === '/risk-intelligence' || route === '/cost-optimization' || route === '/charter-strategy' || route === '/port-compatibility' || route === '/what-if-simulator' || route === '/reports') && <Workspace route={route} risk={risk} congestion={congestion} setCongestion={setCongestion} cargo={cargo} setCargo={setCargo} totalCost={totalCost} strategy={strategy} selectedVessel={selectedVessel} />}
      </section>
      <aside className="rounded-md bg-[#0b1f3a] p-5 text-white"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.1em]"><Waves className="size-4 text-[#58c7b3]" /> Decision engine</div><div className="mt-6 text-3xl font-mono font-semibold">{strategy}</div><p className="mt-3 text-xs leading-5 text-white/60">Rates are projected to soften while vessel supply remains favorable. The model preserves flexibility without sacrificing laycan certainty.</p><div className="mt-6 border-t border-white/10 pt-4 text-xs"><div className="flex justify-between py-2"><span className="text-white/50">Selected vessel</span><b>{selectedVessel}</b></div><div className="flex justify-between py-2"><span className="text-white/50">Port compatibility</span><b className="text-[#58c7b3]">96%</b></div><div className="flex justify-between py-2"><span className="text-white/50">Confidence</span><b>87%</b></div></div></aside>
    </div>
    {notice && <div role="status" className="fixed bottom-5 right-5 z-50 flex items-center gap-2 rounded-md bg-[#0b1f3a] px-4 py-3 text-xs font-semibold text-white shadow-xl"><Check className="size-4 text-[#58c7b3]" /> {notice}</div>}
  </div>
}

function Workspace({ route, risk, congestion, setCongestion, cargo, setCargo, totalCost, strategy, selectedVessel }: any) {
  if (route === '/what-if-simulator') return <div className="grid gap-5"><label className="flex flex-col gap-2"><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#7b8999]">Scenario cargo · {cargo.toLocaleString()} MT</span><input type="range" min="40000" max="120000" step="5000" value={cargo} onChange={(e) => setCargo(Number(e.target.value))} className="accent-[#087cb8]" /></label><div className="grid gap-3 sm:grid-cols-3"><Field label="Vessel" value={selectedVessel} /><Field label="Contract" value="30-day short term" /><label className="flex flex-col gap-2"><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#7b8999]">Port congestion</span><select value={congestion} onChange={(e) => setCongestion(e.target.value)} className="rounded-md border border-[#d7e0ea] bg-[#fbfcfe] px-3 py-2.5 text-sm"><option>Low</option><option>Medium</option><option>High</option></select></label></div></div>
  const items = route === '/port-compatibility' ? [['Draft compatibility', 'COMPATIBLE', '13.2m vessel / 14.5m limit'], ['LOA & beam', 'COMPATIBLE', '225m / 32.2m'], ['Cargo handling', 'COMPATIBLE', '72K MT/day']] : route === '/risk-intelligence' ? [['Freight volatility', `${Math.round(risk * .8)}`, 'Moderate exposure'], ['Vessel availability', '24', '18 ships open'], ['Port congestion', `${congestion === 'High' ? 42 : 18}`, `${congestion} congestion`]] : route === '/charter-strategy' ? [['60% lock now', `${Math.round(cargo * .6).toLocaleString()} MT`, 'Capture certainty'], ['40% optionality', `${Math.round(cargo * .4).toLocaleString()} MT`, 'Retain downside'], ['Expected saving', '$19,200', 'vs. buy now']] : [['Freight cost', `$${Math.round(cargo * 19.8).toLocaleString()}`, 'Base rate'], ['Bunker + port', '$410,000', 'Operating cost'], ['Risk-adjusted total', `$${totalCost.toLocaleString()}`, strategy]]
  return <div className="grid gap-3">{items.map(([label, value, detail]) => <div key={label} className="flex items-center justify-between rounded-md border border-[#e4eaf0] p-4"><div><div className="text-xs font-semibold text-[#0b1f3a]">{label}</div><div className="mt-1 text-[11px] text-[#7b8999]">{detail}</div></div><span className="font-mono text-lg font-semibold text-[#087cb8]">{value}</span></div>)}</div>
}

function Field({ label, value }: { label: string; value: string }) { return <label className="flex flex-col gap-2"><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#7b8999]">{label}</span><input value={value} readOnly className="rounded-md border border-[#d7e0ea] bg-[#fbfcfe] px-3 py-2.5 text-sm text-[#0b1f3a] outline-none" /></label> }
function Kpi({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: typeof Gauge }) { return <div className="rounded-md border border-[#d8dee8] bg-white p-4"><div className="flex items-center justify-between text-[10px] font-semibold uppercase tracking-[.12em] text-[#7b8999]"><span>{label}</span><Icon className="size-4 text-[#087cb8]" /></div><div className="mt-3 font-mono text-xl font-semibold text-[#0b1f3a]">{value}</div><div className="mt-1 text-[11px] text-[#0c9b86]">{detail}</div></div> }
